sudo: required
services:
    - docker

before_install:
    - docker build -t jokingarcia/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jokingarcia/react-test npm test

after_success:
    - docker build -t jokingarcia75/multi-client ./client
    - docker build -t jokingarcia75/multi-nginx ./nginx
    - docker build -t jokingarcia75/multi-server ./server
    - docker build -t jokingarcia75/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push jokingarcia75/multi-client
    - docker push jokingarcia75/multi-nginx
    - docker push jokingarcia75/multi-server
    - docker push jokingarcia75/multi-worker